# Generated by Django 2.2.3 on 2019-08-29 15:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Задача')),
                ('type', models.CharField(choices=[('LOTO', 'Лото'), ('CARDS', 'Карточки'), ('TEST', 'Тест')], default='TEST', max_length=10, verbose_name='Тип')),
                ('date_published', models.DateTimeField(default=datetime.datetime(2019, 8, 29, 15, 47, 47, 962640), verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=datetime.datetime(2019, 8, 29, 15, 47, 47, 962988, tzinfo=utc), verbose_name='Время ответа')),
                ('result', models.IntegerField(default=0, verbose_name='Резултат')),
                ('question_number', models.IntegerField(default=0, verbose_name='Номер последнего вопроса')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathPuzzle.Task')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, verbose_name='Номер вопроса')),
                ('title', models.CharField(default='question', max_length=200, verbose_name='Вопрос')),
                ('date_published', models.DateTimeField(default=datetime.datetime(2019, 8, 29, 15, 47, 47, 963501, tzinfo=utc), verbose_name='Дата публикации')),
                ('type', models.CharField(choices=[('single_answer', 'single_answer'), ('multiply_answer', 'multiply_answer')], default='single_answer', max_length=200, verbose_name='Тип')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathPuzzle.Task')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='answer', max_length=200, verbose_name='Ответ')),
                ('is_right', models.BooleanField(verbose_name='Верный ответ?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathPuzzle.Question')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
