# Generated by Django 2.2.3 on 2019-08-29 15:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mathPuzzle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 29, 15, 47, 53, 400967, tzinfo=utc), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 29, 15, 47, 53, 400098), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='taskresult',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 29, 15, 47, 53, 400447, tzinfo=utc), verbose_name='Время ответа'),
        ),
    ]
